name: PHP Code Sniffer
on: pull_request
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP CodeSniffer
        run: |
          cd my-app
          composer require --dev dealerdirect/phpcodesniffer-composer-installer
      - name: Check coding standards
        run: |
          cd ma-app
          vendor/bin/phpcs